### ISSUE TITLE
UserWarning: Contig names in the coverage file did not match dataset identifiers.

### ISSUE THREAD

**Issue by ngroberts** [blobtoolkit/blobtools2#45]
"UserWarning: Contig names in the coverage file did not match dataset identifiers."

Hello,
I am attempting to add coverage based on a bam file generated from minimap2. However regardless of if I use sed and change the id's to be correct or not I still get this error when using blobtools add --cov.

The reads are HiFi and were assembled with hifiasm.

I generated the mapping data using:
`minimap2 -ax map-hifi -t 16 my_assembly.fasta my_reads.fasta`
`samtools sort -@48 -O BAM output_bam -o output_sorted.bam`

However I still get the above error. If I were to change the contig names in a sam file first > convert to bam > sort. I still get this error. The progress bar reaches about 20-30% and gives me:

> Traceback (most recent call last):
>   File "/home/mysystem/bin/blobtools2/lib/add.py", line 194, in <module>
>     main()
>   File "/home/mysystem/bin/blobtools2/lib/add.py", line 147, in main
>     parsed = field["module"].parse(
>   File "/home/mysystem/bin/blobtools2/lib/cov.py", line 244, in parse
>     fields = parse_bam(
>   File "/home/mysystem/bin/blobtools2/lib/cov.py", line 72, in parse_bam
>     raise UserWarning(
> UserWarning: Contig names in the coverage file did not match dataset identifiers.

I am not sure how else to fix this, I am curious if it is perhaps the way I generated this data. I am not sure. 
A potential workaround could be to instead make a coverage txt file using:
`samtools coverage`
and then adding it as text? I am unsure.

Thank you in advance.

**Comment by rjchallis** [comment]
Sorry about the problems with importing coverage - I've not been able to reproduce the errors others are seeing without the same bam files, but I'm planning to change the internal coverage calculation to call an external tools rather than the current pysam-based implementation to try to make it more reliable.

Meanwhuile, to use samtools coverage instead you could do something like this.

First run samtools coverage on your BAM file.

```
samtools coverage my_assembly.my_reads.bam > my_assembly.my_reads.coverage.txt
```

Then add the coverage file as a text file. The `#rname` column needs to be mapped to `identifier` and the `meandepth` column has the coverage:

```
blobtools add --text my_assembly.my_reads.coverage.txt --text-header --text-cols '#rname=identifier,meandepth=my_reads_cov' my_blobdir
```

Finally, to set the imported coverage as the default y-axis variable for the viewer:

```
blobtools add --key plot.y=my_reads_cov my_blobdir
```

**Comment by ngroberts** [comment]
Thank you very much! I had added it as a text file but was having trouble with adding it as the y-axis. I appreciate the help!
