### ISSUE TITLE
Fasta filtered number incongruent with BTK filtered numbers

### ISSUE THREAD

**Issue by pgonzale60** [blobtoolkit/blobtools2#5]
Hi Rich,

I have an assembly with 21931 fragments. Using 
`./blobtools2/blobtools filter --query-string "http://localhost:8080/view/all/dataset/hs_Omyriophila/blob?bestsumorder_phylum--Keys=2&srtd_cov--Min=0.0100&srtd_cov--Max=300#Filters" --fasta ../clc/hs_Omyriophila_clc_pe_contigs.fasta hs_Omyriophila`
 I expect to get either 18479 or 21931-18479 fragments, but `grep -c ">" ../clc/hs_Omyriophila_clc_pe_contigs.filtered.fasta` returns 177 fragments while, more puzzling, adding the `--invert` tag and repeating the grep command pinpoints 3180 fragments.

Do you know what went wrong?

Cheers,
Pablo

**Comment by rjchallis** [comment]
It looks like I have implemented key-based filtering in exactly opposite ways in the viewer and the command line, so the command is returning only records with the specified key instead of filtering them out. To get the same results at the moment you will need to invert just the key-based filter. If you use the query-string `bestsumorder_phylum--Keys=2&srtd_cov--Min=0.0100&srtd_cov--Max=300&bestsumorder_phylum--Inv=true`, that will give you the results you are expecting.

I need to update this so the filtering here works the same way as the viewer so thanks for pointing this out.

**Comment by rjchallis** [comment]
This should be working as expected now. Please do let me know if you are still experiencing any unexpected behaviour when filtering.
